# netlify.toml
# Налаштування для збірки
[build]
  command = "npm run build"
  publish = "dist"

# Налаштування Production-конфігурації
[[redirects]]
  from = "/api/*"
  to = "https://wishlist-2-nj4d.onrender.com/:splat"
  status = 200
  force = true
